.github/workflows/ci-build.yml
Simple patch to fix the release step.
=> fix release step

.github/workflows/ci-build.yml
Push docs on release rather than on main branch.
=> push docs on release

src/pyansys_sphinx_theme/__init__.py
=> Bump 0.3.dev0 version

src/pyansys_sphinx_theme/__init__.py
=> Bump 0.4.dev0 version

pyproject.toml
Related to https://github.com/pypa/pip/issues/11294. Solves [this CI failure](https://github.com/ansys/ansys-sphinx-theme/runs/7515444077?check_suite_focus=true).
=> Use static description in pyproject.toml

src/ansys_sphinx_theme/__init__.py
=> Bump 0.6.dev0 version

.github/dependabot.yml
Adding ``github-actions`` to Dependabot for automatic update
=> Adding GH actions dependency update

.github/workflows/ci_cd.yml, doc/.vale.ini, doc/source/index.rst, doc/source/options.rst, doc/styles/.gitignore, doc/styles/Vocab/ANSYS/accept.txt
=> Implementing vale

src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
Fix #117 , #112 , #115  #114 #113
=>  Modify css for style changes

src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
Add sphinx design styles to css files.
=> Add style for sphinx design

src/ansys_sphinx_theme/__init__.py
=> Bump 0.7.dev0 version

src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
=> Modify font and scroll bar

src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css, src/ansys_sphinx_theme/static/css/breadcrumbs.css
Add web accessibility theme for dark mode
Add right toc tree padding
=> change right toc tree bd position and dark theme config

src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css, src/ansys_sphinx_theme/theme.conf
=> version switcher styles and config

src/ansys_sphinx_theme/__init__.py
=> Bump version 0.8.dev0

README.rst
=> Solve broken link issue

.pre-commit-config.yaml, pyproject.toml
Wrong reference in PyPI  for home page
=> Wrong reference in PyPI home page

.gitignore, src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
Before patch, 
*  before : https://docs.pyansys.com/index.html
* After :
=> Maintain the sphinx design

src/ansys_sphinx_theme/__init__.py, src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
=> Maintain the contrast styling of sphinx gallery code out.

pyproject.toml
=> Solving broken docs

.github/workflows/ci_cd.yml
Modify dev docs deploy action to deploy on push to main.
=> Modify workflow for dev docs deployment.

.pre-commit-config.yaml, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
=> Fix : web accessibility.

doc/source/user_guide/options.rst
=> Docs: Add examples and link for meilisearch.

src/ansys_sphinx_theme/__init__.py
Fixes typing issue that avoids to properly run the `setup()` function.
=> FIX: typing

doc/source/conf.py, src/ansys_sphinx_theme/__init__.py
Change the default switcher. Make the navigation end bar switcher only if it is present.
=> FIX : Make the switcher optional

src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
=> FIX: Navigation bar drop down styles.

doc/source/user_guide/options.rst
Link is not rendering propely.
=> DOC : Fix typo

doc/source/conf.py, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/breadcrumbs.css
=> FIX : Change the navigation bar style.

.github/workflows/ci_cd.yml
=> MAINT: generating wheelhouse (needed for GH release)

.github/workflows/ci_cd.yml, pyproject.toml, src/ansys_sphinx_theme/__init__.py, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/components/theme-version.html, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/theme.conf
=> fix: sphinx version and update footer

.github/workflows/ci_cd.yml, doc/source/conf.py, pyproject.toml, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/components/search-field.html, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/search.html
Update search.html to read for meilisearch.
=> feat: add the meilisearch webapp service

.github/dependabot.yml, .github/workflows/ci_cd.yml
rename the pyansys/actions to ansys/actions.
=> MAINT: Change the pyansys-actions to ansys-actions

src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
Fix #244 
before : https://sphinxdocs.ansys.com/version/stable/user_guide/404_page.html#create-and-use-a-custom-404-page
=> MAINT: fix the height of sidebars to avoid overflow

.pre-commit-config.yaml, src/ansys_sphinx_theme/latex/404.html, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/components/announcement_version.html, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/components/breadcrumbs.html, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/components/search-field.html, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/components/theme-version.html, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/layout.html, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/search.html
Add html formatter along with the css and js code formatter.
=> Maint: add the html formatter

.github/workflows/ci_cd.yml, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
=> MAINT: adapt the `search hide matches` style for dark and light theme.

doc/source/conf.py
change index from ansys-internal to ansys
=> DOC: rename the index  of meilisearch from library reorg.

src/ansys_sphinx_theme/theme/ansys_sphinx_theme/_templates/autoapi/python/module.rst
This pull-request ensures that all objects inheriting from the 'enum' module of the STD in Python are properly identified.
=> fix: proper filter of enums

src/ansys_sphinx_theme/extension/linkcode.py
https://github.com/ansys/pymapdl/pull/2341 fixes the value error
=> fix: try except to handle value error for linkcode extension 

src/ansys_sphinx_theme/extension/linkcode.py
=> fix: update the extension if condition

src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
https://sphinxdocs.ansys.com/version/dev/examples/index.html
=> fix: styles with sphinx design elements

src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
=> fix: update the styles for sphinx cards

doc/styles/Vocab/ANSYS/accept.txt, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/_templates/autoapi/python/class.rst, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
Fix #317 
Fix #320 
- change the visited link color
- change the underline and underline will be only at time of hovering
=> fix: table background

.pre-commit-config.yaml, doc/source/examples/snippet.py, src/ansys_sphinx_theme/__init__.py, src/ansys_sphinx_theme/examples/__init__.py, src/ansys_sphinx_theme/examples/sample_func.py, src/ansys_sphinx_theme/examples/samples.py, src/ansys_sphinx_theme/examples/type_hint_example.py, src/ansys_sphinx_theme/extension/__init__.py, src/ansys_sphinx_theme/extension/linkcode.py, src/ansys_sphinx_theme/latex/__init__.py
=> feat: add license header

src/ansys_sphinx_theme/latex/__init__.py
=> fix: SyntaxWarning on import

pyproject.toml
Update development version to v0.16.dev0.
=> maint: update development version to v0.16.dev0

doc/source/getting_started/index.rst, pyproject.toml, src/ansys_sphinx_theme/__init__.py
Adds dependencies for API documentation generation with custom templates provided with ansys-sphinx-theme
=> fix: add additional dependencies for autoapi templates

doc/source/user_guide/autoapi.rst, doc/source/user_guide/index.rst
Closes #361
@Revathyvenugopal162 @jorgepiloto - please review thoroughly and feel free to adapt as you prefer.
=> feat: add autoapi docs usage

doc/changelog.d/380.miscellaneous.md, doc/changelog.d/changelog_template.jinja
=> docs: update changelog_template.jinja

doc/changelog.d/386.dependencies.md, pyproject.toml
As tile says, update dev version
=> chore: version 0.17.dev0

doc/changelog.d/388.fixed.md, doc/source/user_guide/autoapi.rst, doc/source/user_guide/index.rst, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
=> fix: update the sphinx design style to disable display of name

.github/workflows/ci_cd.yml, doc/changelog.d/395.fixed.md
I just realized here: https://github.com/ansys/ansys-sphinx-theme/actions/runs/9318514050/job/25651355767#step:4:17
This had to be fixed
=> fix: wrong env var name for PACKAGE_NAME

doc/changelog.d/401.added.md, src/ansys_sphinx_theme/__init__.py, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
=> fix: update the github icon

doc/changelog.d/382.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
| Current    | New |
| ------------- | ------------- |
| ![image](https://github.com/ansys/ansys-sphinx-theme/assets/26918585/a02f5bc0-64f8-40bb-9624-3d2742038cfe) | ![image](https://github.com/ansys/ansys-sphinx-theme/assets/26918585/36c81a6c-8044-47f4-94c3-26fd3ed09052) |
=> fix: Align cheat sheet center

.pre-commit-config.yaml, doc/changelog.d/408.fixed.md, doc/source/examples/nbsphinx/jupyter-notebook.ipynb, doc/source/examples/sphinx-gallery/sphinx-gallery.py, pyproject.toml, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys-sphinx-theme-variable.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/table-custom.css
partially fixes #403
normal state |  hover state | active state
:-------------------------:|:-------------------------:|:-------------------------:
normal state             |  hover state |     active state
:-------------------------:|:-------------------------:|:-------------------------:
normal state             |  hover state |     active state
:-------------------------:|:-------------------------:|:-------------------------:
normal state             |  hover state |     active state
:-------------------------:|:-------------------------:|:-------------------------:
normal state             |  hover state |     active state
:-------------------------:|:-------------------------:|:-------------------------:
normal state             |  hover state |     active state …
=> fix: reformat the table styles

doc/changelog.d/411.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys-sphinx-theme-variable.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/pydata-sphinx-theme-custom.css
fix sidebar in association with #403
- visited link and visited hovered
- link and link hovered
- active and hover
=> fix: `primary` ,`secondary` sidebars and links

README.rst, doc/changelog.d/418.dependencies.md, pyproject.toml, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys-sphinx-theme-variable.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/breadcrumbs.css
=> fix: update the breadcrumbs

doc/changelog.d/422.dependencies.md, doc/source/conf.py, doc/source/links.rst, doc/source/user-guide/configuration.rst, doc/styles/config/vocabularies/ANSYS/accept.txt, pyproject.toml, src/ansys_sphinx_theme/__init__.py, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/theme.conf
=> feat: add default logo and update logo option with theme

doc/changelog.d/431.fixed.md, src/ansys_sphinx_theme/__init__.py
=> fix: updated the logo options

doc/changelog.d/438.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys-sphinx-theme-variable.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/pydata-sphinx-theme-custom.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/sphinx-design.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/sphinx-gallery.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/table-custom.css
> [!NOTE]  
> Second button is with hover
=> fix: dark theme variables

.github/workflows/ci_cd.yml, doc/changelog.d/446.fixed.md
Resolve the syntax error in package name fix for https://github.com/ansys/ansys-sphinx-theme/actions/runs/10299970659/job/28508754310
=> fix: stable docs indexing package name

doc/changelog.d/448.dependencies.md, pyproject.toml
=> maint: version 1.1.dev0

doc/source/user-guide/options.rst, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys-sphinx-theme-variable.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/sphinx-design.css
=> fix: sphinx design image background

doc/changelog.d/460.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/pydata-sphinx-theme-custom.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/sphinx-gallery.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/table-custom.css
- before ![image](https://github.com/user-attachments/assets/a51f19dc-695e-486c-b871-90e556f206f3)
- After ![image](https://github.com/user-attachments/assets/01e23396-0376-4fdc-a91e-46d1dc328004)
=> fix: tables and cell output

doc/changelog.d/469.fixed.md, doc/source/user-guide/configuration.rst, src/ansys_sphinx_theme/__init__.py, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/theme.conf
=> feat: add default logo links for Ansys and PyAnsys logos

doc/changelog.d/471.fixed.md, doc/source/conf.py, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/sphinx-gallery.css
=> fix: download icon with sphinx-gallery and nbsphinx

doc/changelog.d/497.fixed.md, src/ansys_sphinx_theme/search/fuse_search.py
=> fix: the anchor url of search with the switcher version

src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys-sphinx-theme-variable.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/fuse-search.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/pydata-sphinx-theme-custom.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/js/fuse_search.js
=> fix: style for smaller media

doc/changelog.d/514.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/pydata-sphinx-theme-custom.css
=> fix: navigation end columns

doc/changelog.d/518.dependencies.md, pyproject.toml
=> chore: bump version 1.2.dev0

.github/workflows/ci_cd.yml, .github/workflows/label.yml, doc/changelog.d/519.fixed.md
=> fix: update the token and email of bot for changelog actions

doc/changelog.d/524.documentation.md, doc/source/user-guide/options.rst
=> docs: adding ``title`` in example section

CONTRIBUTORS.md, doc/changelog.d/529.fixed.md
=> fix: contributors file

.github/labels.yml, doc/changelog.d/535.maintenance.md
=> chore: add hacktoberfest labels

.github/labels.yml, doc/changelog.d/549.maintenance.md
This pull-request introduces three new labels. These can be used to tag CSS, JS, and UI/UX related tasks.
=> ci: add new labels

.github/labels.yml, doc/changelog.d/560.miscellaneous.md
Continuation of the feedback given by @SMoraisAnsys in #558
=> fix: typos

.github/workflows/ci_cd.yml, doc/changelog.d/568.miscellaneous.md, doc/source/getting-started/installation.rst, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/pydata-sphinx-theme-custom.css
=> fix: change the display of math rendering

doc/changelog.d/602.miscellaneous.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/components/theme-version.html
=> fix:  typo in date variable for last modified

.pre-commit-config.yaml, LICENSE, doc/changelog.d/608.maintenance.md, doc/source/examples/snippet.py, doc/source/examples/sphinx-gallery/sphinx-gallery.py, src/ansys_sphinx_theme/__init__.py, src/ansys_sphinx_theme/examples/__init__.py, src/ansys_sphinx_theme/examples/sample_func.py, src/ansys_sphinx_theme/examples/samples.py, src/ansys_sphinx_theme/examples/type_hint_example.py, src/ansys_sphinx_theme/extension/__init__.py, src/ansys_sphinx_theme/extension/autoapi.py, src/ansys_sphinx_theme/extension/linkcode.py, src/ansys_sphinx_theme/latex/__init__.py, src/ansys_sphinx_theme/search/__init__.py, src/ansys_sphinx_theme/search/fuse_search.py
This pull-request updates the pre-commit hooks. It also updates the license headers.
=> fix: style and license headers

doc/changelog.d/617.documentation.md, doc/source/user-guide/options.rst, src/ansys_sphinx_theme/__init__.py
=> Fix: optimize imports for whatsnew

doc/changelog.d/638.documentation.md, doc/source/index.rst
=> docs: add contribute page in toctree

.github/workflows/ci_cd.yml, doc/changelog.d/654.fixed.md
fix  the deploy issue to https://github.com/ansys/ansys-sphinx-theme/actions/runs/13943602579
=> fix: update the changelog action only for PR

doc/changelog.d/680.added.md, src/ansys_sphinx_theme/__init__.py
Add <meta property="og:site_name" content="PyAnsys" /> to support Dev Portal search and Open Graph integration, with correct indentation.
=> feat: add metatag content

doc/changelog.d/686.fixed.md, pyproject.toml
This requires a quick patch release and resolution
Closes #685
=> fix: block snowbalstemmer <3 for now

.github/workflows/ci_cd.yml, doc/source/conf.py
. The search sections from title case to sentence case.
=> fix: the search title case to sentence case

.github/workflows/ci_cd.yml, doc/changelog.d/717.maintenance.md
=> ci: update the actions to commit hash

.github/workflows/ci_cd.yml, doc/changelog.d/766.maintenance.md
=> ci: add `trusted publishers pypi release`

doc/changelog.d/785.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/components/navbar-nav.html
=> fix: style fixes with navigation dropdown
