ansys/ansys-sphinx-theme

.github/workflows/ci-build.yml, .github/workflows/style.yml, pyansys_sphinx_theme/_version.py
Prepare release branch by bumping to 0.1.dev0.  Also, minor fix to ensure docs are only deployed on tags.
=> deploy on tag; bump to 0.1.dev0

doc/source/coding_style.rst
This PR adds to the Coding Style and Best Practices documentation. The new section describes some of the set up for doctest and how to use it with docstring examples.
=> Add docstring example best practices to doc

doc/source/coding_style.rst
Fix mismatched headings so that all sections fall under parent section "Docstring Examples Best-Practice"
=> Update headings for docstring examples best practices

doc/source/coding_style.rst
Remove use of "Please" and the extra space in deprecation warning example, following Kathy's edits to these deprecation warnings in use in pyaedt.
=> Reword deprecation warning examples

pyansys_sphinx_theme/static/css/theme.css
Adds some custom styling to improve the grouping and readability of generated API docs. Side by side comparison (current on left, proposed on right):
There's less space between 'Parameters' and 'Examples', and more space between 'Examples' and the methods. This helps the examples feel more like they belong to the class itself, as opposed to the method below.
I'm not a CSS expert, but I think the selectors are appropriate and seem to align with how the styling is written in the base sphinx package. These changes have been tested on the example API Documentation in this package, and on the as-yet-unreleased grantami-bomanalytics package.
=> Improve API doc empty-space formatting

pyansys_sphinx_theme/static/css/theme.css
Hi there
Since we would like to use Pandas DataFrame to present data in PyMAPDL documentation, I thought we might as well include the style in the Pyansys Theme.
The proposal is shown as this:
I'm happy to do any changes you might propose. I just tried the colors align with Ansys color theme.
=> Added style to table representation

pyansys_sphinx_theme/static/css/theme.css
I'm not super happy about the readability of the text rendered as code:
And some people (@RomanIlchenko1308 ) have already pointed out that the size looks smaller than the rest of the body text.
Quick fix is to increase the font-size a bit (to 15.5px) so we can improve readability and visual impact.
However, I'm partial to change the font altogether. I personally like ``Roboto condensed Light`` [Link]  (size: normal (15px))(https://fonts.google.com/specimen/Roboto+Condensed?preview.text=package,%20ansys-mapdl-core,%20pro&preview.text_type=custom):
Or even better ``consolas`` (size: normal (15px)):
=> Rethinking code style

doc/source/usage.rst, src/pyansys_sphinx_theme/docs-navbar.html, src/pyansys_sphinx_theme/icon-links.html, src/pyansys_sphinx_theme/theme.conf
Resolves #38 by adding:
These changes are not really needed but this would imply having the following in our `conf.py` in order to hide an icon:
```python
html_theme_options = {
"github_url": "",
...
}
```
With this PR, we get a better syntax:
```python
html_theme_options = {
"show_icons": False,
}
```
Also, we can better control individual icon display by name:
```python
html_theme_options = dict(
icon_links = [dict(name="...", url="...", icon="..."), ]
hidden_icons = ["GitHub"],
)
=> Allow users to show or hide havbar icons

.pre-commit-config.yaml
Don't check if you're merging main on github because github merges on main.
Pinging @jorgepiloto for visibility.
=> disable checking main

src/pyansys_sphinx_theme/__init__.py
fix #55  wrong nav-bar text and link colors
=> fix nav-bar text and links

doc/source/usage.rst
Add documentation for how to use cover page customization for PDF.
=> add documentation for using coverpage

.github/workflows/label.yml, README.rst, doc/source/coding_style.rst, doc/source/conf.py, doc/source/style.rst, doc/source/usage.rst, pyproject.toml, tox.ini
=> Solving references to PyAnsys

pyproject.toml, src/ansys_sphinx_theme/theme.conf
Update `pydata-sphinx-theme` to latest version. It should solve https://github.com/pyansys/pymapdl/pull/1167
I do not have write-access to this repo so I had to fork.
=> Updata pydata-sphinx-theme.

doc/make.bat
Modified make.bat file  to take all .tex file to build pdf (without interaction).
=> Modify make.bat file to build pdf with all .tex file

src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
This PR will fix the code output cell color of sphinx gallery. in dark mode. Light mode color retained as it is. 
The shade/color of texts and the background will change soon as discussed with documentation team once they are ready with the color codes.
=> Change the color of output cell for sphinx-gallery

doc/source/conf.py, doc/source/usage.rst, requirements/requirements_doc.txt, src/ansys_sphinx_theme/__init__.py, src/ansys_sphinx_theme/static/404.rst, src/ansys_sphinx_theme/theme.conf
Resolves #72 by including a basic 404 page.
=> Ship a basic 404 page

src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
=> Modify css for better web accessibility

src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
``<strong>``  tags are set to bolder but it was not showing bold. Font-weight: bolder means "One relative font weight heavier than the parent element" ([MDN article](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#values)). So giving ``strong`` tag to font_weight : 900 directly. Fix #79
=> Fix bold to ``<strong>`` tags

README.rst
Fix the link for pyansys-dev-guide as it updated to how-to section.
=> Fix link for contribution in README

.gitignore, doc/source/installation.rst, src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css, src/ansys_sphinx_theme/static/css/breadcrumbs.css
This PR is to add some of changes suggested by @timdansys as listed below:
=> Modify font style and size

tox.ini
We forgot to update the content of CNAME content when we migrated this from PyAnsys to Ansys organization.
This commit should be merged into main and then cherry-picked into release/0.5, @Revathyvenugopal162.
=> Fix CNAME in tox.ini

src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
=> Inline code color changes from pink to black

src/ansys_sphinx_theme/type_hint_example.py
Adding function using type hinting to be used in dev-guide as example.
=> Add type hint example function

.pre-commit-config.yaml, doc/source/conf.py, requirements/requirements_doc.txt, src/ansys_sphinx_theme/static/404.rst, src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
=> Maintain edit this button style and version switcher

doc/source/conf.py, doc/source/index.rst, doc/source/user_guide/404_page.rst, src/ansys_sphinx_theme/__init__.py, src/ansys_sphinx_theme/latex/404.html, src/ansys_sphinx_theme/latex/__init__.py
=> Feat: Customizing 404 page

src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
Fix broken version switch styling.
=> Fix version switcher styling

doc/Makefile, doc/make.bat
Rename `doc/build` to `doc/_build`.
=> FIX: build name

src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
=> Add sphinx dropdown styles

src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
Quick update for the nav bar styling in favor of only PyMAPDL.
=> Update the nav bar format.

doc/source/getting_started/index.rst, src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
=> Add the deprecation styles

.flake8, .github/workflows/ci_cd.yml, .pre-commit-config.yaml, README.rst, doc/source/conf.py, doc/source/user_guide/index.rst, src/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css, src/ansys_sphinx_theme/static/css/breadcrumbs.css
=> Update the styles for new version

src/ansys_sphinx_theme/__init__.py
=> Accepting semver regex in a better way

src/ansys_sphinx_theme/__init__.py, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/_templates/autosummary/class.rst
=> Add the default navigation collapse with the theme.

.github/workflows/ci_cd.yml
=> Fix: The priority of workflow.

.github/workflows/ci_cd.yml, doc/source/conf.py, doc/source/user_guide/options.rst, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/components/search-field.html, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/theme.conf
This pull-request allows to use the default meilisearch credentials for PyAnsys public documentation. Note this API key is already public, no need to hide it.
=> DOC: use default meilisearch credentials

doc/source/conf.py, doc/source/examples/sphinx-design.rst, doc/source/getting_started/index.rst, pyproject.toml, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
Resolve part of #256 
- The sphinx card with content in footer is having the issue with  screen size, so adapted only for the card header 
and size. https://cheatsheets.docs.pyansys.com/ rendering very good on all screen.
- Update the script to render all examples of the card inside the example section for manual check and also as examples
- Adapt the icon with same font size
=> MAINT: Add sphinx card configuration according to screen size

doc/source/conf.py, src/ansys_sphinx_theme/__init__.py, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/meilisearch.css
meilisearch will not accept the index having `.` it will only accept the index with `-`.
###
=> MAINT:  Change the index-uid compactible with search-index

src/ansys_sphinx_theme/theme/ansys_sphinx_theme/components/search-field.html, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/search.html
there was a size issue with search bar on second page as search heading is align right as below
In this PR, 
* fix that right allignment
* increase the search limit to max(1000)
=> doc: update the limit and size of search bar.

doc/source/examples/table.rst, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
=> maint: fix normal table rendering styles

src/ansys_sphinx_theme/__init__.py, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/components/edit-this-page.html
=> fix: rename the extension name with no conflict

src/ansys_sphinx_theme/theme/ansys_sphinx_theme/components/search-field.html, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/search.html, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/meilisearch.css
=> Fix: retain the style of having shortcut tip in search bar

doc/source/user_guide/options.rst
=> fix: remove the deleted link and add the version docs for pymeilisearch

pyproject.toml, src/ansys_sphinx_theme/__init__.py
=> feat: bump version 0.12.dev0

src/ansys_sphinx_theme/theme/ansys_sphinx_theme/_templates/autoapi/python/module.rst
Fixes the unicode symbol used for exceptions when using sphinx-autoapi templates. This should be patched released into 0.11.1.
=> fix: unicode char for exceptions

.github/workflows/ci_cd.yml, doc/source/conf.py, pyproject.toml, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/components/search-field.html, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/meilisearch.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/js/meilisearch_theme_wrap.js
make sure you are searching by adding spinner
https://github.com/ansys/ansys-sphinx-theme/assets/104772255/03661c50-56b4-4dbc-a640-ed6eac864a53
=> fix: limit and spinning of search icon

doc/source/examples/index.rst, doc/source/examples/sphinx-design.rst, tox.ini
This pull-request fixes the indentation of the `Examples` section. As an example, consider:
**Before**
**After**
Same applies for the examples in the "sphinx-design.rst" page.
=> fix: examples indentation

src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/theme.conf
Fixes #340 by adding default light and dark themes.
I am more than happy to continue the discussion in this thread. It may be possible that UI/UX can raise concerns about these.
What is true is that the contrast is better:
- Content: white on black (dark) and black on white (light)
- **We can improve docstrings and comments (not very readable)**: gray on black (dark) light blue on white (light)
Old dark             |  New dark
:-------------------------:|:-------------------------:
Old light             |  New light
:-------------------------:|:-------------------------:
=> feat: add default pygment themes friendly (light) and monokai (dark)

src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
Fixes #342. Uses the right color for the selected theme:
=> fix: color for topic directive

src/ansys_sphinx_theme/theme/ansys_sphinx_theme/_templates/autoapi/python/class.rst, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/_templates/autoapi/python/module.rst
Includes the new templates for ``sphinx-autoapi==3.1.0.a2``. These new templates need to be added in a new minor release since they introduce breaking changes.
=> feat: update templates for sphinx-autoapi==3.1.0a2

src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
Corrected display issue where function and property prefixes inside a class were improperly shown, e.g., `FooObject` --> `bar_property` displayed as `FooObject.bar_property` in the `FooObject` class instead of `bar_property`. This PR disables prefix display to maintain consistency with the function name only.
=> fix: Update ``autoapi`` style to for disabling ``prename`` display.

.github/workflows/ci_cd.yml, doc/changelog.d/378.fixed.md
add changelog actions in ci-cd, continuation of #370
=> fix: add changelog action in ci-cd

doc/changelog.d/393.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys_sphinx_theme.css
fix #392 
In the Sphinx design, the `sd-hide-link-text` class had a font size of 0. When we were overriding the size of the card, the entire size got overridden. I changed the size back to normal, and hopefully, this will work. relevant code here: [GitHub link](https://github.com/executablebooks/sphinx-design/blob/a3bdfa3742c25a7261a8301dfbb2a09e9700d325/style/_button.scss#L91).
tested locally
=> fix:  sphinx design card font size

doc/changelog.d/407.miscellaneous.md, src/ansys_sphinx_theme/__init__.py
As title says, the function is defined twice with the same content.
=> refactor: remove function duplicate

doc/changelog.d/427.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/pydata-sphinx-theme-custom.css
Small continuation of https://github.com/ansys/ansys-sphinx-theme/pull/411. Ensures that no borders and scroll bars are displayed in any of the sidebars. Matches the style proposed in this comment https://github.com/ansys/ansys-sphinx-theme/issues/403#issuecomment-2179532890
=> fix: sidebar borders and overflow

doc/changelog.d/439.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/sphinx-design.css
=> fix: sphinx card `box shadow` on focus

doc/changelog.d/442.fixed.md, doc/source/user-guide/configuration.rst, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ansys-sphinx-theme-variable.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/meilisearch.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/pydata-sphinx-theme-custom.css
=> fix: search bar style for dark theme, icons links

doc/changelog.d/452.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/pydata-sphinx-theme-custom.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/sphinx-design.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/table-custom.css
fit the content based on the content length, keep 400px as min width
https://github.com/user-attachments/assets/71d82269-a8da-45d7-9ee3-23b635a4b50c
=> fix: minor style changes

doc/changelog.d/474.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/pydata-sphinx-theme-custom.css
The sidebar scrolls only appear if there is sidebar content is more than the page height. fix #468
=> fix: the scrollbar on sidebar

doc/changelog.d/477.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/pydata-sphinx-theme-custom.css
=> fix: admonitions styles for ``topic`` admonition

.github/workflows/ci_cd.yml, .pre-commit-config.yaml, README.rst, doc/changelog.d/480.dependencies.md, doc/changelog.d/482.dependencies.md, doc/source/conf.py, doc/source/examples/nbsphinx/jupyter-notebook.ipynb, doc/source/examples/snippet.py, pyproject.toml, src/ansys_sphinx_theme/__init__.py, src/ansys_sphinx_theme/examples/sample_func.py, src/ansys_sphinx_theme/examples/samples.py, src/ansys_sphinx_theme/examples/type_hint_example.py, src/ansys_sphinx_theme/extension/autoapi.py, src/ansys_sphinx_theme/extension/linkcode.py, src/ansys_sphinx_theme/latex/__init__.py, tox.ini
- **Pre-commit Hooks:** Replaced  with `ruff` for linting and formatting in favour of migrating ``sphinx-url`` extension.
- **README Cleanup:** Updated the README for better clarity and removed outdated content.
- **Python 3.9:** Dropped support for Python 3.9 as per the new compatibility guidelines.
- **Tox Configuration:** Modified `tox.ini` to align with the updated Python versions and tools.
=> maint: update tooling, cleanup and drop python 3.9

doc/changelog.d/490.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/sphinx-gallery.css
continuation of #489 
Here the download buttons are misaligned https://sphinxdocs.ansys.com/version/dev/examples/gallery-examples/sphinx-gallery.html#render-a-table-in-markdown
This PR will fix the issue
=> fix: the download in sphinx gallery

doc/changelog.d/495.added.md, doc/source/user-guide/autoapi.rst, src/ansys_sphinx_theme/extension/autoapi.py
The members are ordered by source rather than alphabetically, so this change should allow people to organize their documentation in alphabetical order if they want
autoapi_member_order: https://sphinx-autoapi.readthedocs.io/en/latest/reference/config.html#confval-autoapi_member_order
=> feat: add member_order to autoapi

doc/changelog.d/503.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/nbsphinx.css
This pull-request removes the caption within the body content created by the `nbgallery` extension. The caption rendered within the sidebar is still present.
=> fix: do not display captions for nbgallery

.github/workflows/ci_cd.yml, doc/changelog.d/517.fixed.md
Updates the CI/CD to use Ansys actions v8. To be cherry-picked into the `release/1.1` branch.
=> fix(ci): update to Ansys actions v8

doc/changelog.d/542.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/js/fuse_search.js
fix #539 
1. Pressing Enter without typing anything in the search bar will take you to the PyData search page.
2. Pressing Enter on any of the entries in the suggestion bar will take you to the corresponding anchor.
3. After typing a search query, if the suggestions aren't enough, pressing Enter will take you to the PyData search page.
=> fix: add default `enter` for search

doc/changelog.d/554.fixed.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/pydata-sphinx-theme-custom.css
=> fix: padding for toctree entry in sidebar

doc/changelog.d/553.documentation.md, doc/source/conf.py, doc/source/examples/nbsphinx/jupyter-notebook.ipynb, doc/source/index.rst
This pull-request fixes https://github.com/ansys/ansys-sphinx-theme/issues/526 when the ``BUILD_EXAMPLES=true`` environment variable is set.
=> doc: allow developer to skip examples build

.github/workflows/ci_cd.yml
This pull-request fixes the issues raise in <https://github.com/ansys/ansys-sphinx-theme/actions/runs/11459431277/job/31935828742>, where the ``doc-changelog`` action fails when trying to create a fragment outside of a pull-request.
=> fix: changelog action

doc/changelog.d/580.documentation.md, doc/source/user-guide/options.rst
Switch the default value of `show_prev_next` to True in the theme options documentation.
The reason for this change is that the prev / next buttons are useful for navigating the documentation, especially in narrow viewports.
In that case, the only other option to navigate is the hamburger menu, which the user may not be aware of.
=> Enable 'show_prev_next' in the documented defaults

doc/changelog.d/584.miscellaneous.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/components/search-button-field.html, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/css/ast-search.css, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/js/pydata_search.js, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/js/search.js
fixes #581 
**Enhancements to Search Functionality:**
1. "Enter" Key Navigation to First Result:
- Pressing "Enter" now directly navigates to the first search result.
- If no search results are found, pressing "Enter" redirects the user to a PyData search interface.
2. Local HTML File Search for Development:
-   In local environments, the search function now works seamlessly with local HTML files, allowing developers to use PyData's search capabilities locally.
=> fix: enable local page `Search` and default to PyData search on 'Enter'

doc/changelog.d/594.miscellaneous.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/components/theme-version.html
The `Date class` or ``date module``, if referenced in the API documentation, had all its docstrings replaced with the build date due to a conflict with the date variable in JavaScript, which caused only the date to render in the documentation. In the PR, the date variable was renamed to `ast_build_date` to resolve this issue.. reported by @jorgepiloto
=> fix: rename the ``date`` to ``ast_build_date`` in js

doc/changelog.d/603.miscellaneous.md, pyproject.toml
Because of the current upper limit, we got affected by the latest release of pydata-sphinx-theme in the form of a small section in the right sidebar:
This should fix it, forcing dependabot to open a new pull-request for us to adapt.
=> fix: impose upper version for the pydata-sphinx-theme

doc/changelog.d/630.miscellaneous.md, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/_templates/autoapi/python/class.rst
Found this typo when there was a change in a library with a nested class using the template, which caused it to fail to render.
The macro was defined as `render_autosummary_template `and used in the function as `autosummary_template`, which caused the issue.
=> fix: typo in autoapi template

.github/dependabot.yml, .gitignore, CONTRIBUTING.md, doc/changelog.d/636.documentation.md, doc/source/conf.py, doc/source/contribute.rst, doc/source/contribute/developer.rst, doc/source/contribute/user.rst, doc/source/index.rst, doc/source/links.rst, pyproject.toml, tox.ini
=> docs: add contribute section

.flake8, doc/changelog.d/641.miscellaneous.md, doc/changelog.d/changelog_template.jinja
This pull-request removes the configuration file for `.flake8`. We are fully supporting Ruff, so it makes no sense to keep this file around.
=> fix: remove flake8 configuration file

doc/changelog.d/642.added.md, doc/source/conf.py, doc/source/contribute/developer.rst, package.json, pyproject.toml, tox.ini
This PR introduces a new Tox environment, `[testenv:doc-serve]`, to build and serve the documentation locally. 
1. Adds [testenv:doc-serve] to build and serve docs locally.
2. Uses stb serve for live preview.
3. Includes necessary dependencies and environment setup.
4. Helps in testing documentation changes more efficiently.
=> feat: Add Tox environment for documentation preview

doc/changelog.d/655.fixed.md, src/ansys_sphinx_theme/__init__.py
=> fix: change logging info to error in quarto build

doc/changelog.d/656.miscellaneous.md, doc/source/user-guide/options.rst, doc/styles/config/vocabularies/ANSYS/accept.txt, src/ansys_sphinx_theme/__init__.py, src/ansys_sphinx_theme/cheatsheet.py, src/ansys_sphinx_theme/whatsnew.py
This PR improves the modularity and maintainability of the code by:
- Moved all `cheatsheet`-related functions to a new module called `whatsnew.py`
- Moved all `whatsnew`-related functions to another module called `cheatsheet.py`
- Removed these functions from `__init__.py` to maintain a cleaner structure.
- Reordered the sidebar , keeping cheatsheet to appear first on the sidebar, if both whatsnew and cheatsheet present 
- Ensures that `cheatsheet` and `whatsnew` are appended to the sidebar in the order specified by the ux
- Add Note in docs for these change.
- Improves **code organization** by separating concerns.
- Enhances **maintainability** by avoiding clutter in `__init__.py`.
- #620 
> [!IMPORTANT]
> No breaking changes 
<details><summary>Images</summary>
<p>
</p>
</details>
=> refactor: cheatsheet and whatsnew functions into separate modules and implement sidebar ordering

doc/changelog.d/658.fixed.md, src/ansys_sphinx_theme/cheatsheet.py
Quarto writes both stdout and stderr to stderr so we need to log it as info if it's not an error
error noticed in https://github.com/ansys/pymapdl/actions/runs/14087805194/job/39456752974?pr=2346#step:22:189
=> fix: quarto error logging

doc/changelog.d/691.added.md, src/ansys_sphinx_theme/__init__.py, src/ansys_sphinx_theme/assets/styles/ansys-sphinx-theme.scss
- Center navbar elements
- Centering `bd-content` container. This is more obvious when we hide any of the sidebars.
- Moving search bar to `navbar_end` so it hides when there is no space. This change probably needs some thoughts. Since the search bar "disappear" for small screens and gets located in the primary sidebar:
=> feat: small layout adjustments

doc/changelog.d/693.fixed.md, src/ansys_sphinx_theme/assets/styles/ansys-sphinx-theme.scss, src/ansys_sphinx_theme/assets/styles/pydata-sphinx-theme-custom.scss
As the title.
See #692
Just changed the font weight to bold, and removed transparency
=> fix: style for back to top button

README.rst
I noticed that this repository is using ruff after watching black badge in README.rst.
=> Update README.rst to fix label from black to ruff

doc/changelog.d/721.fixed.md, src/ansys_sphinx_theme/assets/styles/ast-search.scss, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/static/js/search-main.js
The highlight on search makes the codeblocks to bold, https://acp.docs.pyansys.com/version/dev/user_guide/howto/copy_objects.html. In this PR, 
- Remove the weight to highlight in general
- Rename the highlight class to search-highlight
=> fix: remove font weight on highlight

doc/changelog.d/728.fixed.md, doc/source/conf.py, src/ansys_sphinx_theme/extension/autoapi.py
This PR removes all AutoAPI-related options from the theme configuration to avoid conflicts and duplication in the pickled environment as mentioned in issue #725 . While we can't fully achieve a zero-config setup—since some settings like html_permalinks_icon and html_theme_options come from PyData Sphinx Theme and others like html_static_path from extensions like sphinx-design— and many mores from nbsphinx, this change ensures that only the core AutoAPI configuration (autoapi_prepare_jinja_env) is preserved. This simplifies the environment and prevents outdated theme-based config overrides.
=> fix: cache of autoapi options with ansys sphinx theme

doc/changelog.d/744.fixed.md, src/ansys_sphinx_theme/assets/styles/pydata-sphinx-theme-custom.scss
fix #548 
This PR Intended to change the font from `open-sans
` to ``monospace`` in the literal code blocks as shown in image below:
=> fix(style): update the literal  `codespace` to `monospace` font

doc/changelog.d/755.fixed.md, src/ansys_sphinx_theme/search/__init__.py, src/ansys_sphinx_theme/search/fuse_search.py
fix #730
This pull request removes a deprecated theme option (`index_patterns`) from the codebase and updates related functionality and documentation. The changes clean up the code and ensure that the deprecated feature is no longer supported.
=> fix: remove deprecated theme option from code base

doc/changelog.d/758.added.md, doc/source/user-guide/configuration.rst, src/ansys_sphinx_theme/theme/ansys_sphinx_theme/layout.html
This pull request introduces functionality to support multiple physics tags in the PyAnsys HTML metadata. The changes include updates to both the documentation and the HTML layout template to handle lists of physics tags.
=> feat: add multiple tags for `meta-data`
